apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: /applications
    apps.open-cluster-management.io/reconcile-rate: high
  name: applications-subscription
  namespace: acm-poc-policies
spec:
  channel: acm-poc-channel/acm-poc-channel
  placement:
    local: true
  