apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: /policies
  name: poc1
  namespace: acm-poc1
spec:
  channel: acm-poc-channel/acm-poc-channel
  placement:
    local: true
  