apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-acm-poc-rbac

placementRef:
  name: placement-acm-poc-rbac
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io

subjects:
- name: acm-poc-role-projet-a-dev-musthave
  kind: Policy
  apiGroup: policy.open-cluster-management.io

- name: acm-poc-role-projet-a-dev-mustonlyhave
  kind: Policy
  apiGroup: policy.open-cluster-management.io