apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-acm-poc-gk-operator

spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: acm-poc-gk-operator, operator: In, values: ["yes"]}
