apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-acm-poc-gk-constraints

placementRef:
  name: placement-acm-poc-gk-constraints
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io

subjects:
- name: policy-gatekeeper-check-label-template
  kind: Policy
  apiGroup: policy.open-cluster-management.io

- name: policy-gatekeeper-check-label-constraint
  kind: Policy
  apiGroup: policy.open-cluster-management.io

- name: policy-gatekeeper-audit-label-constraint
  kind: Policy
  apiGroup: policy.open-cluster-management.io

- name: policy-gatekeeper-check-service-type-constraint
  kind: Policy
  apiGroup: policy.open-cluster-management.io

- name: policy-gatekeeper-check-service-type-template
  kind: Policy
  apiGroup: policy.open-cluster-management.io