apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-acm-poc-np

placementRef:
  name: placement-acm-poc-np
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io

subjects:
- name: policy-np-frontend-backend
  kind: Policy
  apiGroup: policy.open-cluster-management.io

- name: policy-np-multiple-ns
  kind: Policy
  apiGroup: policy.open-cluster-management.io
