apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-default

spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: []
