apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-acm-poc-namespace
  namespace: acm-poc-policies

spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: acm-poc-namespace, operator: In, values: ["yes"]}
