apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-acm-poc-np-default

placementRef:
  name: placement-acm-poc-np
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io

subjects:
- name: policy-default-demo-ns-np
  kind: Policy
  apiGroup: policy.open-cluster-management.io