apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-openshift

placementRef:
  name: placement-openshift
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io

subjects:
- name: restricted-scc
  kind: Policy
  apiGroup: policy.open-cluster-management.io
