apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-gk-check-service-type-constraint
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-gk-check-service-type-constraint
      spec:
        remediationAction: inform
        severity: high
        object-templates:

          - complianceType: musthave
            objectDefinition:

              apiVersion: constraints.gatekeeper.sh/v1beta1
              kind: K8sCFServiceType
              metadata:
                name: k8scfservicetype
              spec:
                enforcementAction: dryrun
                match:
                  kinds:
                  - apiGroups:
                    - ""
                    kinds:
                    - Service
                  namespaces:
                  - gatekeeper-test
                parameters:
                  unallowedporttype:
                  - NodePort



