apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-np-multiple-ns
  annotations:
    policy.open-cluster-management.io/standards: Securité infrastructure
    policy.open-cluster-management.io/categories: Network security
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-np-multiple-ns
      spec:
        remediationAction: inform
        severity: high
        namespaceSelector:
          include: ["namespace-test-projectx-*"]
        object-templates:

          - complianceType: mustonlyhave
            objectDefinition:
    
              apiVersion: networking.k8s.io/v1
              kind: NetworkPolicy
              metadata:
                name: default-network-policy-projectx
              spec:
                podSelector:
                  matchLabels:
                    role: backend
                ingress:
                  - from:
                      - podSelector:
                          matchLabels:
                            role: frontend
                    ports:
                      - protocol: TCP
                        port: 9002

