apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-acm-poc1
  namespace: acm-poc-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: poc, operator: In, values: ["poc1"]}