apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: test-mustnothave
  annotations:
    policy.open-cluster-management.io/categories: Securité infrastructure
    policy.open-cluster-management.io/controls: Configurations
    policy.open-cluster-management.io/standards: NIST-CSF
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: test-restricted-mustnothave
        spec:
          namespaceSelector:
            exclude:
            - "openshift-*"
            include:
            - "test-mustnothave"
            - "test-mustnothave2"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: networking.k8s.io/v1
                kind: NetworkPolicy
                metadata:
                  name: example
                spec:
                  podSelector:
                    matchLabels:
                      role: db
                  ingress:
                    - ports:
                        - protocol: TCP
                          port: 6379
                      from:
                        - namespaceSelector:
                            matchLabels:
                              project: myproject
                        - podSelector:
                            matchLabels:
                              role: somerole
                  policyTypes:
                    - Ingress
          remediationAction: inform
          severity: high

